# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 965e38769fc68f2ba5b1eb8eccabf13fd37bb0ae369ad66ad13ca4466c150b5ec9b7a4d379d25d66bfc304633777c304639e6bffc48cb6b0556664a42258c42e

test:
  secret_key_base: 979e566db4268630739306fa4f82ac6c4a5482a61b1e645b28db7123e7de27474247cd84711082ea9332ce58d273ad4d1a35e19bf6aa287599bbc19d5275afd1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
